------
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpdrs
  labels:
    app: Rered
    env: dev
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: Rered
      env: dev
  template:
    metadata:
      name: podrs
      labels:
        app: Rered
        env: dev
   spec:
     containers:
     - name: apache
       image: httpd:alpine3.23   
       ports:
       - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apachesvc
  labels:
    app: Rered
    env: dev
spec:
  selector:
    app: Rered
  type: NodePort
  ports:
  - name: httpdport
    port: 80
    nodeport: 30000
    targetPort: 80