---
apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  -  name: mysql
     image: mysql:8.0-debian
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: admin123
     - name: MYSQL_USERNAME
       value: nop
     - name: MYSQL_DATABASE
       value: emp
     - name: MYSQL_PASSWORD
       value: admin123
