---
apiVersion:	v1
kind: Pod
metadata:
  name: resourcepod
spec:
  containers:
  - name: resourcecontainer
    image: jenkins/jenkins:2.486-jdk17
    ports:
    - containerPort: 8080
      name: jenkins_port
      protocol: TCP
    resources:
      requests:
        memory: 1Gi
        cpu: 512m
      limits:
       memory: 2Gi
       cpu: 1000m
   
